### ISSUE TITLE
Wrong output with \n and multiple spaces

### ISSUE THREAD

**Issue by FlavaSava7** [Tanjoodo/squaretext#1]
1 - wrong output with \n : 
e.g. 
```
input=   a
                    w

output = W 
              A 
            A W 
            A W 
```

2- Multiple spaces:
 

**Solution** is to **insert** line before **24** : 
`source = source.replace(/\n/g, "");`
And **replace** line 24 with : 
`source = source.replace(/ /g, "");`

[source](https://stackoverflow.com/a/832276/4391766)

**Comment by Tanjoodo** [comment]
Cool thanks for the source. Though maybe next time do it yourself
